
package com.weil.webservice.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServiceDemoService", targetNamespace = "http://service.webservice.weil.com", wsdlLocation = "http://localhost:8080/webservice/webservice?wsdl")
public class WebServiceDemoService_Service
    extends Service
{

    private final static URL WEBSERVICEDEMOSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICEDEMOSERVICE_EXCEPTION;
    private final static QName WEBSERVICEDEMOSERVICE_QNAME = new QName("http://service.webservice.weil.com", "WebServiceDemoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/webservice/webservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICEDEMOSERVICE_WSDL_LOCATION = url;
        WEBSERVICEDEMOSERVICE_EXCEPTION = e;
    }

    public WebServiceDemoService_Service() {
        super(__getWsdlLocation(), WEBSERVICEDEMOSERVICE_QNAME);
    }

    public WebServiceDemoService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICEDEMOSERVICE_QNAME, features);
    }

    public WebServiceDemoService_Service(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICEDEMOSERVICE_QNAME);
    }

    public WebServiceDemoService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICEDEMOSERVICE_QNAME, features);
    }

    public WebServiceDemoService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceDemoService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceDemoService
     */
    @WebEndpoint(name = "WebServiceDemoServiceImplPort")
    public WebServiceDemoService getWebServiceDemoServiceImplPort() {
        return super.getPort(new QName("http://service.webservice.weil.com", "WebServiceDemoServiceImplPort"), WebServiceDemoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceDemoService
     */
    @WebEndpoint(name = "WebServiceDemoServiceImplPort")
    public WebServiceDemoService getWebServiceDemoServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.webservice.weil.com", "WebServiceDemoServiceImplPort"), WebServiceDemoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICEDEMOSERVICE_EXCEPTION!= null) {
            throw WEBSERVICEDEMOSERVICE_EXCEPTION;
        }
        return WEBSERVICEDEMOSERVICE_WSDL_LOCATION;
    }

}
